In [68]:
# Import required libraries and dependencies
import pandas as pd
import hvplot.pandas
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [69]:
# Load the data into a Pandas DataFrame
df_market_data = pd.read_csv(
    "Resources/crypto_market_data.csv",
    index_col="coin_id")

# Display sample data
df_market_data.head(10)

price_change_percentage_24h  price_change_percentage_7d  \
coin_id                                                                    
bitcoin                              1.08388                     7.60278   
ethereum                             0.22392                    10.38134   
tether                              -0.21173                     0.04935   
ripple                              -0.37819                    -0.60926   
bitcoin-cash                         2.90585                    17.09717   
binancecoin                          2.10423                    12.85511   
chainlink                           -0.23935                    20.69459   
cardano                              0.00322                    13.99302   
litecoin                            -0.06341                     6.60221   
bitcoin-cash-sv                      0.92530                     3.29641   

                 price_change_percentage_14d  price_change_percentage_30d  \
coin_id                                                                     
bitcoin                              6.57509                      7.67258   
ethereum                             4.80849                      0.13169   
tether                               0.00640                     -0.04237   
ripple                               2.24984                      0.23455   
bitcoin-cash                        14.75334                     15.74903   
binancecoin                          6.80688                      0.05865   
chainlink                            9.30098                    -11.21747   
cardano                              5.55476                     10.10553   
litecoin                             7.28931                      1.21662   
bitcoin-cash-sv                     -1.86656                      2.88926   

                 price_change_percentage_60d  price_change_percentage_200d  \
coin_id                                                                      
bitcoin                             -3.25185                      83.51840   
ethereum                           -12.88890                     186.77418   
tether                               0.28037                      -0.00542   
ripple                             -17.55245                      39.53888   
bitcoin-cash                       -13.71793                      21.66042   
binancecoin                         36.33486                     155.61937   
chainlink                          -43.69522                     403.22917   
cardano                            -22.84776                     264.51418   
litecoin                           -17.23960                      27.49919   
bitcoin-cash-sv                    -24.87434                       7.42562   

                 price_change_percentage_1y  
coin_id                                      
bitcoin                            37.51761  
ethereum                          101.96023  
tether                              0.01954  
ripple                            -16.60193  
bitcoin-cash                       14.49384  
binancecoin                        69.69195  
chainlink                         325.13186  
cardano                           156.09756  
litecoin                          -12.66408  
bitcoin-cash-sv                    93.73082

In [70]:
# Generate summary statistics
df_market_data.describe()

price_change_percentage_24h  price_change_percentage_7d  \
count                    41.000000                   41.000000   
mean                     -0.269686                    4.497147   
std                       2.694793                    6.375218   
min                     -13.527860                   -6.094560   
25%                      -0.608970                    0.047260   
50%                      -0.063410                    3.296410   
75%                       0.612090                    7.602780   
max                       4.840330                   20.694590   

       price_change_percentage_14d  price_change_percentage_30d  \
count                    41.000000                    41.000000   
mean                      0.185787                     1.545693   
std                       8.376939                    26.344218   
min                     -18.158900                   -34.705480   
25%                      -5.026620                   -10.438470   
50%                       0.109740                    -0.042370   
75%                       5.510740                     4.578130   
max                      24.239190                   140.795700   

       price_change_percentage_60d  price_change_percentage_200d  \
count                    41.000000                     41.000000   
mean                     -0.094119                    236.537432   
std                      47.365803                    435.225304   
min                     -44.822480                     -0.392100   
25%                     -25.907990                     21.660420   
50%                      -7.544550                     83.905200   
75%                       0.657260                    216.177610   
max                     223.064370                   2227.927820   

       price_change_percentage_1y  
count                   41.000000  
mean                   347.667956  
std                   1247.842884  
min                    -17.567530  
25%                      0.406170  
50%                     69.691950  
75%                    168.372510  
max                   7852.089700

In [71]:
# Plot your data to see what's in your DataFrame
df_market_data.hvplot.line(
    width=800,
    height=400,
    rot=90
)

:NdOverlay   [Variable]
   :Curve   [coin_id]   (value)

---

### Prepare the Data

In [72]:
# Use the `StandardScaler()` module from scikit-learn to normalize the data from the CSV file
scaled_data= StandardScaler().fit_transform(df_market_data)

In [73]:
# Create a DataFrame with the scaled data
df_market_data_scaled= pd.DataFrame(
   scaled_data,
   columns= df_market_data.columns 
)

# Copy the crypto names from the original data
df_market_data_scaled["coin_id"]= df_market_data.index 

# Set the coinid column as index
df_market_data_scaled= df_market_data_scaled.set_index("coin_id")

# Display sample data
df_market_data_scaled.head()

price_change_percentage_24h  price_change_percentage_7d  \
coin_id                                                                 
bitcoin                          0.508529                    0.493193   
ethereum                         0.185446                    0.934445   
tether                           0.021774                   -0.706337   
ripple                          -0.040764                   -0.810928   
bitcoin-cash                     1.193036                    2.000959   

              price_change_percentage_14d  price_change_percentage_30d  \
coin_id                                                                  
bitcoin                          0.772200                     0.235460   
ethereum                         0.558692                    -0.054341   
tether                          -0.021680                    -0.061030   
ripple                           0.249458                    -0.050388   
bitcoin-cash                     1.760610                     0.545842   

              price_change_percentage_60d  price_change_percentage_200d  \
coin_id                                                                   
bitcoin                         -0.067495                     -0.355953   
ethereum                        -0.273483                     -0.115759   
tether                           0.008005                     -0.550247   
ripple                          -0.373164                     -0.458259   
bitcoin-cash                    -0.291203                     -0.499848   

              price_change_percentage_1y  
coin_id                                   
bitcoin                        -0.251637  
ethereum                       -0.199352  
tether                         -0.282061  
ripple                         -0.295546  
bitcoin-cash                   -0.270317

---

### Find the Best Value for k Using the Original Data.

In [74]:
# Create a list with the number of k-values from 1 to 11
k= range (1, 12)
list (k)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [75]:
# Create an empty list to store the inertia values
inertia=[]

# Create a for loop to compute the inertia with each possible value of k
# Inside the loop:
# 1. Create a KMeans model using the loop counter for the n_clusters
# 2. Fit the model to the data using `df_market_data_scaled`
# 3. Append the model.inertia_ to the inertia list
for i in k:
    k_model= KMeans(n_clusters=i)
    k_model.fit(df_market_data_scaled)
    inertia.append (k_model.inertia_)

inertia

c:\Users\Joanna\anaconda3\envs\my_python\Lib\site-packages\sklearn\cluster\_kmeans.py:1446: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
c:\Users\Joanna\anaconda3\envs\my_python\Lib\site-packages\sklearn\cluster\_kmeans.py:1446: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
c:\Users\Joanna\anaconda3\envs\my_python\Lib\site-packages\sklearn\cluster\_kmeans.py:1446: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
c:\Users\Joanna\anaconda3\envs\my_python\Lib\site-packages\sklearn\cluster\_kmeans.py:14

[287.0,
 198.57181809798124,
 147.4299807404537,
 79.02243535120975,
 66.09918779091186,
 58.947700056162915,
 50.187099148623496,
 37.28818726271725,
 34.71134474633814,
 36.77452483791707,
 24.499701220180288]

In [76]:
# Create a dictionary with the data to plot the Elbow curve
dic_inertia= {'k':k, 'inertia':inertia}

# Create a DataFrame with the data to plot the Elbow curve
inertia_df= pd.DataFrame(dic_inertia)

inertia_df

k     inertia
0    1  287.000000
1    2  198.571818
2    3  147.429981
3    4   79.022435
4    5   66.099188
5    6   58.947700
6    7   50.187099
7    8   37.288187
8    9   34.711345
9   10   36.774525
10  11   24.499701

In [77]:
# Plot a line chart with all the inertia values computed with 
# the different values of k to visually identify the optimal value for k.

inertia_plot= inertia_df.hvplot(
    x = "k",
    y="inertia",
    title= "Comparing Inertia and Number of Clusters in Standardized Performance Data",
    xlabel= "Number of Clusters(k)",
    ylabel = "Inertia (units)",
    xticks = k
)
inertia_plot

:Curve   [k]   (inertia)

#### Answer the following question: 

**Question:** What is the best value for `k`?

**Answer:** The best value for k is 4 because there is a signifant reduction from 232.054 in k=2  to 79.022 in k=4

---

### Cluster Cryptocurrencies with K-means Using the Original Data

In [78]:
# Initialize the K-Means model using the best value for k
model= KMeans(n_clusters= 4, random_state= 0 )

In [79]:
# Fit the K-Means model using the scaled data
model.fit (df_market_data_scaled)

c:\Users\Joanna\anaconda3\envs\my_python\Lib\site-packages\sklearn\cluster\_kmeans.py:1446: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


KMeans(n_clusters=4, random_state=0)

In [80]:
# Predict the clusters to group the cryptocurrencies using the scaled data
clusters= model.predict(df_market_data_scaled)

# Print the resulting array of cluster values.
clusters

array([2, 2, 0, 0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 0, 2, 0, 0, 2, 0, 0, 2,
       0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 2, 0, 0, 3, 0, 0, 0, 0])

In [81]:
# Create a copy of the DataFrame
df_market_data_scaled_prediction = df_market_data_scaled.copy()

In [82]:
# Add a new column to the DataFrame with the predicted clusters
df_market_data_scaled_prediction['Cluster_Original']= clusters

# Display sample data
df_market_data_scaled_prediction.head()

price_change_percentage_24h  price_change_percentage_7d  \
coin_id                                                                 
bitcoin                          0.508529                    0.493193   
ethereum                         0.185446                    0.934445   
tether                           0.021774                   -0.706337   
ripple                          -0.040764                   -0.810928   
bitcoin-cash                     1.193036                    2.000959   

              price_change_percentage_14d  price_change_percentage_30d  \
coin_id                                                                  
bitcoin                          0.772200                     0.235460   
ethereum                         0.558692                    -0.054341   
tether                          -0.021680                    -0.061030   
ripple                           0.249458                    -0.050388   
bitcoin-cash                     1.760610                     0.545842   

              price_change_percentage_60d  price_change_percentage_200d  \
coin_id                                                                   
bitcoin                         -0.067495                     -0.355953   
ethereum                        -0.273483                     -0.115759   
tether                           0.008005                     -0.550247   
ripple                          -0.373164                     -0.458259   
bitcoin-cash                    -0.291203                     -0.499848   

              price_change_percentage_1y  Cluster_Original  
coin_id                                                     
bitcoin                        -0.251637                 2  
ethereum                       -0.199352                 2  
tether                         -0.282061                 0  
ripple                         -0.295546                 0  
bitcoin-cash                   -0.270317                 2

In [83]:
# Create a scatter plot using hvPlot by setting 
# `x="price_change_percentage_24h"` and `y="price_change_percentage_7d"`. 
# Color the graph points with the labels found using K-Means and 
# add the crypto name in the `hover_cols` parameter to identify 
# the cryptocurrency represented by each data point.

plot_original_cluster = df_market_data_scaled_prediction.hvplot.scatter(

    x = "price_change_percentage_24h",
    y = "price_change_percentage_7d",
    by = 'Cluster_Original',
    title = "Cryptocurrencies Standarized Returns. K-Mean Clusters with k=4.",
    hover_cols = 'coin_id' 
)
plot_original_cluster

:NdOverlay   [Cluster_Original]
   :Scatter   [price_change_percentage_24h]   (price_change_percentage_7d,coin_id)

---

### Optimize Clusters with Principal Component Analysis.

In [84]:
# Create a PCA model instance and set `n_components=3`.
pca = PCA(n_components= 3)

# Bring back to original data
df_market_data_scaled_no_clusters = df_market_data_scaled_prediction.drop(columns='Cluster_Original')

In [85]:
# Use the PCA model with `fit_transform` to reduce to 
# three principal components.
market_data_pca= pca.fit_transform(df_market_data_scaled_prediction)
# View the first five rows of the DataFrame. 
market_data_pca[0:5]

array([[ 1.19408229, -0.90207402, -0.58533763],
       [ 1.00970605, -0.66358438, -1.13695032],
       [-0.72253591, -0.30763241,  0.7218133 ],
       [-0.74826646, -0.33237895,  0.55847869],
       [ 2.25853853, -1.82696614, -1.37816649]])

In [86]:
# Retrieve the explained variance to determine how much information 
# can be attributed to each principal component.
pca.explained_variance_ratio_

array([0.37269822, 0.32489961, 0.18917649])

#### Answer the following question: 

**Question:** What is the total explained variance of the three principal components?

**Answer:** 
Explained variance of the first principal component: 0.37269822
Explained variance of the second principal component: 0.32489961
Explained variance of the third principal component: 0.18917649

In [87]:
# Assuming coin id contains cryptoccurrencies
coin_id= ["bitcoin, ethereum, tether, ripple, bitcoin-cash"]

# Create a new DataFrame with the PCA data
PCA_data_df = pd.DataFrame(
    market_data_pca,
    columns=["PC1", "PC2", "PC3"] 
)
# Copy the crypto names from the original data
PCA_data_df['coin_id'] = df_market_data_scaled.index

# Set the coinid column as index
PCA_data_df= PCA_data_df.set_index('coin_id')

# Display sample data
PCA_data_df.head()


PC1       PC2       PC3
coin_id                                   
bitcoin       1.194082 -0.902074 -0.585338
ethereum      1.009706 -0.663584 -1.136950
tether       -0.722536 -0.307632  0.721813
ripple       -0.748266 -0.332379  0.558479
bitcoin-cash  2.258539 -1.826966 -1.378166

---

### Find the Best Value for k Using the PCA Data

In [88]:
# Create a list with the number of k-values from 1 to 11
k = list(range(1,12))
k

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [89]:
# Create an empty list to store the inertia values
inertia_pca = []

# Create a for loop to compute the inertia with each possible value of k
# Inside the loop:
# 1. Create a KMeans model using the loop counter for the n_clusters
# 2. Fit the model to the data using `df_market_data_pca`
# 3. Append the model.inertia_ to the inertia list

for i in k:
    model_pca = KMeans (n_clusters = i)
    model_pca.fit(PCA_data_df)
    inertia_pca.append(model_pca.inertia_)

inertia_pca

c:\Users\Joanna\anaconda3\envs\my_python\Lib\site-packages\sklearn\cluster\_kmeans.py:1446: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
c:\Users\Joanna\anaconda3\envs\my_python\Lib\site-packages\sklearn\cluster\_kmeans.py:1446: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
c:\Users\Joanna\anaconda3\envs\my_python\Lib\site-packages\sklearn\cluster\_kmeans.py:1446: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
c:\Users\Joanna\anaconda3\envs\my_python\Lib\site-packages\sklearn\cluster\_kmeans.py:14

[290.0184568161519,
 199.10805307785176,
 135.12170445033505,
 43.58643281714782,
 35.06010302455465,
 28.200339504780708,
 19.33388835769815,
 17.094804091491973,
 12.842813015254169,
 9.937094210829077,
 8.036013722365889]

In [90]:
# Create a dictionary with the data to plot the Elbow curve
inertia_pca = {'k':k, 'inertia_pca': inertia_pca}
# Create a DataFrame with the data to plot the Elbow curve
inertia_pca_df= pd.DataFrame(inertia_pca)

inertia_pca_df = inertia_pca_df.set_index('k')
inertia_pca_df

inertia_pca
k              
1    290.018457
2    199.108053
3    135.121704
4     43.586433
5     35.060103
6     28.200340
7     19.333888
8     17.094804
9     12.842813
10     9.937094
11     8.036014

In [91]:
# Plot a line chart with all the inertia values computed with 
# the different values of k to visually identify the optimal value for k.

inertia_pca_plot = inertia_pca_df['inertia_pca'].hvplot(
    title  = 'Principal Components of the Standarized Performance: Inertia vs Number of Clusters',
    xlabel = 'Number of Clusters (k)',
    ylabel = 'Inertia (units)',
    xticks= k     
)

inertia_pca_plot

:Curve   [k]   (inertia_pca)

#### Answer the following questions: 

* **Question:** What is the best value for `k` when using the PCA data?

  * **Answer:** The best value for the number of clusters k is 4.


* **Question:** Does it differ from the best k value found using the original data?

  * **Answer:**  No,  in the original data the k-value was k=4 with an inertia of 79.022. When using the PCA data the k-value is k=4 but with an inertia of 43.586

### Cluster Cryptocurrencies with K-means Using the PCA Data

In [92]:
# Initialize the K-Means model using the best value for k
k = 4
model_pca = KMeans(n_clusters=4, random_state=0)

In [93]:
# Fit the K-Means model using the PCA data
model_pca.fit(PCA_data_df)

c:\Users\Joanna\anaconda3\envs\my_python\Lib\site-packages\sklearn\cluster\_kmeans.py:1446: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


KMeans(n_clusters=4, random_state=0)

In [94]:
# Predict the clusters to group the cryptocurrencies using the PCA data
cluster = model_pca.predict(PCA_data_df)

# Print the resulting array of cluster values.
cluster

array([1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 1, 0, 0, 3, 0, 0, 0, 0])

In [95]:
# Create a copy of the DataFrame with the PCA data
PCA_data_df_copy= PCA_data_df.copy()

# Add a new column to the DataFrame with the predicted clusters
PCA_data_df_copy['Predicted_Cluster']= clusters

# Display sample data
PCA_data_df_copy.head()

PC1       PC2       PC3  Predicted_Cluster
coin_id                                                      
bitcoin       1.194082 -0.902074 -0.585338                  2
ethereum      1.009706 -0.663584 -1.136950                  2
tether       -0.722536 -0.307632  0.721813                  0
ripple       -0.748266 -0.332379  0.558479                  0
bitcoin-cash  2.258539 -1.826966 -1.378166                  2

In [96]:
# Create a scatter plot using hvPlot by setting 
# `x="PC1"` and `y="PC2"`. 
# Color the graph points with the labels found using K-Means and 
# add the crypto name in the `hover_cols` parameter to identify 
# the cryptocurrency represented by each data point.

scatter_plot = PCA_data_df_copy.hvplot.scatter(

    x = "PC1",
    y = "PC2",
    by = 'Predicted_Cluster',
    title = "PCA Scatter Plot with Predicted Clusters",
    hover_cols = coin_id 
)
scatter_plot

:NdOverlay   [Predicted_Cluster]
   :Scatter   [PC1]   (PC2)

### Visualize and Compare the Results

In this section, you will visually analyze the cluster analysis results by contrasting the outcome with and without using the optimization techniques.

In [97]:
# Composite plot to contrast the Elbow curves
inertia_plot + inertia_pca_plot

:Layout
   .Curve.I           :Curve   [k]   (inertia)
   .Curve.Inertia_pca :Curve   [k]   (inertia_pca)

In [98]:
# Composite plot to contrast the clusters
# YOUR CODE HERE!
plot_original_cluster + scatter_plot

:Layout
   .NdOverlay.I  :NdOverlay   [Cluster_Original]
      :Scatter   [price_change_percentage_24h]   (price_change_percentage_7d,coin_id)
   .NdOverlay.II :NdOverlay   [Predicted_Cluster]
      :Scatter   [PC1]   (PC2)

#### Answer the following question: 

  * **Question:** After visually analyzing the cluster analysis results, what is the impact of using fewer features to cluster the data using K-Means?

  * **Answer:** Reducing the number of features results in decreased inertia. In the present analysis, using three components led to a variance reduction of approximately 45.57%, correlating with a similar reduction in inertia (from 79 to 43). Such reduction might typically suggest a need to adjust the optimal number of clusters. However, intriguingly, this was not the case here. Both the original and PCA clusters consisted of the same number (4) of clusters. Remarkably, beneath the PCA Scatter Plot, clusters are distinctly delineated within their respective groups, enhancing visualization and comprehension.